# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - avansprogrammeren4API

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip src package*.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: share-a-meal
      DB_USER: root
      DB_PASSWORD: root
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for tests
        run: unzip release.zip

      - name: Start MySQL connection from host
        run: |
          sudo /etc/init.d/mysql start
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
          mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE \`${{ env.DB_NAME }}\`;"

      - name: Import the database
        run: |
          echo "USE \`${{env.DB_NAME}}\`;" | cat - src/database/sql-files/share-a-meal.sql | mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}}

      - name: Install dependencies
        run: npm install

      - name: npm test
        run: |
          npm test -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_NAME --DB_PORT $DB_PORT

  deploy:
    runs-on: ubuntu-latest
    needs: integration_tests
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3E4872C9449943EA8DC994263064A739 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C00F59559A104361A0C3BBBD253C6D6C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_30EC4017DF47405FABB4AA807EF1BDF5 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "avansprogrammeren4API"
          slot-name: "Production"
          package: .
